apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    name: schema-registry-service
    app: wh-stream-app
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    name: schema-registry-pod
    app: wh-stream-app